services:
  open-webui:
    container_name: ${CONTAINER_NAME:-open-webui}
    image: ghcr.io/open-webui/open-webui:ollama
    restart: ${RESTART_POLICY:-always}
    volumes:
      - ollama:/root/.ollama
      - open-webui:/app/backend/data
    ports: 
      - "${APP_PORT:-8000}:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  ollama:
  open-webui: